# Site settings
title: DiversifyCAZymes
email: diversifycazymes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   The website for DiversifyCAZymes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://DiversifyCAZymes.github.io" # the base hostname & protocol for your site
twitter_username: DiverseCAZymes
github_username:  DiversifyCAZymes
array: []

# Build settings
markdown: kramdown

collections:
  instructors:
    output: true
  workshops:
    output: true
  news:
    output: true
